### ISSUE TITLE
Alternative to vscode settings

### ISSUE THREAD

**Issue by andig** [nwisbeta/validate-yaml-schema#10]
It would be nice to add a list of files/ schemas to apply contained in the workspace without needing to add the vscode settings as it might contain other content that is not relevant for publishing on github.

**Comment by velsietis** [comment]
I remember I left a [TODO comment](https://github.com/nwisbeta/validate-yaml-schema/blob/3ccf3931eb024726dc2ed5ab575bfadb48ecf315/src/yaml-validator.ts#L25) for this.  Should be a pretty quick, I'll take a look

**Comment by andig** [comment]
Much appreciated. Ideally I‘d like to specify a glob (though I need a single file only) and have that validated.

**Comment by andig** [comment]
ping @velsietis any chance to take a look? Really waiting for this action to be able to validate my config (and hence its schema) during build :)

**Comment by velsietis** [comment]
Hey, completely forgot.  Just created a new release, so you can now supply your own config file location:
```
      - uses: nwisbeta/validate-yaml-schema@v1.0.2
        with: 
          settingsFile: path/to/myConfig.json
```

**Comment by andig** [comment]
That is still very indirect. Would it be possible to just specify a `schema` and `files` glob instead of going through a settings file?

**Comment by velsietis** [comment]
Could do, but if I understand you right that would only let you use one schema.  Is that right?

Just checking, because with the `yaml.schemas` part of the settings you can set up multiple schemas.  However, I think it's tricky to accomplish that with Action inputs as they're strings rather than structured data.

A single schema and file glob is ok though, let me know if I that's what you meant.

**Comment by andig** [comment]
> A single schema and file glob is ok though, let me know if I that's what you meant.

Perfect for my purpose. If i want more I could still call the action once more with different settings. If you want to go that way it would take care of having to create a settings file just to validate another one (assuming both yaml and schema are already in git).

> However, I think it's tricky to accomplish that with Action inputs as they're strings rather than structured data.

Ah, never looked into coding actions. They don't support exposing the yaml settings structure?

**Comment by velsietis** [comment]
Actually when I thought about it, it's pretty easy to supply the config.  I've put out another release v1.0.3.

Instead of adding the `yaml.schemas` config to a file, you can now supply it as inline JSON, e.g.:

```yaml
      - uses: nwisbeta/validate-yaml-schema@v1.0.3
        with:
          yamlSchemasJson: |
            {
                "http://json.schemastore.org/composer": ["/*"],
                "file:///home/johnd/some-schema.json": ["some.yaml"],
                "../relative/path/schema.json": ["/config*.yaml"],
                "/Users/johnd/some-schema.json": ["some.yaml"],
            }
```
Just need to make sure you get the yaml indentation right for a multi-line string

**Comment by andig** [comment]
Sounds good, but can't get it to work:

    Run nwisbeta/validate-yaml-schema@v1.0.3
    with:
        yamlSchemasJson: {
        "file://schema.json": ["evcc.dist.yaml"]
    }

        settingsFile: .vscode/settings.json
    /home/runner/work/evcc/evcc/evcc.dist.yaml
    [{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":1}},"message":"Unable to load schema from '/': .","severity":2,"code":768,"source":"YAML"}]
    evcc.dist.yaml
    Warning: Invalid Files: evcc.dist.yaml
    Error: Schema validation failed on one or more YAML files.
    
Here's the details: https://github.com/andig/evcc/runs/1689712556

**Comment by velsietis** [comment]
Change it to a relative path.
```
{
    "./schema.json": ["evcc.dist.yaml"]
}
```
I think the way you've got it, it's looking for the schema in the root of the actions environment, but it's actually at the root of your github workspace

**Comment by andig** [comment]
Ahhh..... thank you so much!!!!
