### ISSUE TITLE
allow declaring files that are expected to fail

### ISSUE THREAD

**Issue by ssbarnea** [nwisbeta/validate-yaml-schema#12]
As part of validation of schemas we do not only want to pass a list of files/patterns that are expected to be validated but among these we also have files that we know that should fail validation, so when schemas are updated we assure they still catch those bad examples.

As current input is the `yamlSchemasJson` block which only contains schemas and file patterns, maybe we need another argument like:
```
expected_result:
  passed: ["foo.yml"]
  failed: ["bar.yml"]
```

If the outcome is not the expected one, that action should fail.

BTW, thanks for taking time to write this action, it is really useful for validating schemas.

**Comment by velsietis** [comment]
Might take a while for us to get round to looking at this, but feel free to send a Pull Request :)

**Comment by ssbarnea** [comment]
Yep, I will likely propose a PR that does this now that I know it will not be an undesired feature to have.

**Comment by velsietis** [comment]
Thanks for your suggestion. Unfortunately, I don't have time to keep maintaining this repo and I have now delisted the action from the marketplace and I'm closing all issues before archiving the repo.

You're welcome to use the code, please see the deprecation notice in the [README](https://github.com/nwisbeta/validate-yaml-schema/#readme)
