### ISSUE TITLE
relative schema paths work with yamlSchemasJson but not with settings.json

### ISSUE THREAD

**Issue by ssbarnea** [nwisbeta/validate-yaml-schema#13]
Based on the README, I assumes that using settings.json would work the same way as passing `yamlSchemasJson` with the extra benefit of also enabling the schemas inside vscode itself.

While originally it passed, with something like below it decided to fail without mentioning which files or schemas failed:
```
{
    "yaml.schemas": {
        "./f/ansible-galaxy.json": ["examples/**/galaxy.yml"],
    }
}
```
[Output](https://pipelines.actions.githubusercontent.com/rekSs6Ys941PBwDzidvwmgxAHAr4HUnbd16NDetmnR4RTaYK7J/_apis/pipelines/1/runs/157/signedlogcontent/5?urlExpires=2021-05-03T16%3A45%3A59.1225837Z&urlSigningMethod=HMACV1&urlSignature=bX%2B4VaNXVgj6k%2Fs7qaIojO27EpK8EB%2Bs%2Fx9VD3k2Mdw%3D):
```
Run nwisbeta/validate-yaml-schema@v1.0.3
/home/runner/work/schemas/schemas

Warning: Invalid Files: /home/runner/work/schemas/schemas
Error: Schema validation failed on one or more YAML files.
```

**Comment by velsietis** [comment]
That's odd.  It should work the same way (that's how we're using it in our [API Catalogue](https://github.com/nwisbeta/api-catalogue/blob/master/.vscode/settings.json).

Can you share a bit more detail to help replicate the issue? A link to an example repo would be good.

**Comment by ssbarnea** [comment]
Sorry for late reply, i was in vacation. This was really caused by myself as I forgot to add the checkout step before running the action, and that is what happens when it runs inside an empty directory. Yep, "invalid files" really translates to "files not found".
