### ISSUE TITLE
Empty files are considered valid

### ISSUE THREAD

**Issue by SoftCreatR** [nwisbeta/validate-yaml-schema#19]
It seems, that empty YAML files are considered valid, which is, in my humble opinion, incorrect.

**Comment by velsietis** [comment]
Sorry that you've had issues using this action. Unfortunately, I don't have time to keep maintaining this repo and I have now delisted the action from the marketplace and I'm closing all issues before archiving the repo.

You're welcome to use the code, please see the deprecation notice in the [README](https://github.com/nwisbeta/validate-yaml-schema/#readme)
