### ISSUE TITLE
Validation always returns true and logs error

### ISSUE THREAD

**Issue by muravitskiy** [nwisbeta/validate-yaml-schema#24]
## Description

Validation fails because [language settings](https://github.com/nwisbeta/validate-yaml-schema/blob/master/src/schema-validator.ts#L17) are missing yaml version. We can get it from `./vscode/settings.json` (`"yaml.yamlVersion"`, default "1.2")

```ts
private languageSettings : LanguageSettings = {
    validate: true, // Turn on validation, turn off everything else
    hover: false,
    completion: false,
    format: false,
    isKubernetes: false,
    // <-- add `yamlVersion` here
    schemas: [],
    customTags: []
  };
```
The error is `Error: Expected '1.1' or '1.2' as version, but found: undefined`

## Info

- version 2.0.0

**Comment by velsietis** [comment]
Sorry that you've had issues using this action. Unfortunately, I don't have time to keep maintaining this repo and I have now delisted the action from the marketplace and I'm closing all issues before archiving the repo.

You're welcome to use the code, please see the deprecation notice in the [README](https://github.com/nwisbeta/validate-yaml-schema/#readme)
